# -*- coding: utf-8 -*-
"""LEDteste

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FkoNa31kP-qn5EMDtZb7sNl5A9E_5e1j
"""

import RPi.GPIO as GPIO
import time

LED_AMARELO = 16  # Número do pino GPIO conectado ao LED
LED_VERMELHO = 20
LED_VERDE = 21
i = 0 #contador

#configuração inicial
GPIO.setmode(GPIO.BCM)
GPIO.setup(LED_AMARELO, GPIO.OUT)
GPIO.setup(LED_VERMELHO, GPIO.OUT)
GPIO.setup(LED_VERDE, GPIO.OUT)

while(i<5): #repete 5x
    
    #liga e desliga dos leds
    GPIO.output(LED_VERMELHO, GPIO.HIGH)
    time.sleep(2)
    GPIO.output(LED_VERMELHO, GPIO.LOW)

    GPIO.output(LED_VERDE, GPIO.HIGH)
    time.sleep(1)
    GPIO.output(LED_VERDE, GPIO.LOW)

    GPIO.output(LED_AMARELO, GPIO.HIGH)
    time.sleep(1)
    GPIO.output(LED_AMARELO, GPIO.LOW)
    
    i=i+1

#desconectando as portas GPIO
GPIO.cleanup()
